import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'AI for Leaders',
      className: 'sidebar-track',
      link: { type: 'doc', id: 'ai-for-leaders/genai-for-everyone/intro' },
      items: [
        {
          type: 'category',
          label: 'AI for Everyone — Gen AI & use cases',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-leaders/genai-for-everyone/intro' },
          items: [
            'ai-for-leaders/genai-for-everyone/intro',
            'ai-for-leaders/genai-for-everyone/literacy-and-the-road-to-generative-ai',
            'ai-for-leaders/genai-for-everyone/five-layer-ai-stack',
            'ai-for-leaders/genai-for-everyone/ai-model-lifecycle-for-leaders',
            'ai-for-leaders/genai-for-everyone/llm-design-case-study',
          ],
        },
        {
          type: 'category',
          label: 'Prompt Engineering',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-leaders/prompt-engineering/introduction' },
          items: [
            'ai-for-leaders/prompt-engineering/introduction',
            'ai-for-leaders/prompt-engineering/design-of-a-prompt',
            'ai-for-leaders/prompt-engineering/language-models-are-few-shot-learners',
            'ai-for-leaders/prompt-engineering/hallucinations-in-large-language-models',
            'ai-for-leaders/prompt-engineering/hands-on-prompt-design-webapp-cursor',
            'ai-for-leaders/prompt-engineering/building-digital-assets-tutorial',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI for Engineering',
      className: 'sidebar-track',
      items: [
        { type: 'html', value: '<span class="sidebar-divider">Foundations</span>' },
        {
          type: 'category',
          label: 'Deep Neural Networks',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/deep-neural-networks/intro' },
          items: [
            'ai-for-engineering/deep-neural-networks/perceptron-and-neuron',
            'ai-for-engineering/deep-neural-networks/layers-in-deep-neural-networks',
            'ai-for-engineering/deep-neural-networks/activation-functions',
            'ai-for-engineering/deep-neural-networks/loss-functions',
            'ai-for-engineering/deep-neural-networks/forward-pass',
            'ai-for-engineering/deep-neural-networks/backward-pass',
            'ai-for-engineering/deep-neural-networks/trainable-parameters-and-hyperparameters',
            'ai-for-engineering/deep-neural-networks/overfitting-in-neural-networks',
            'ai-for-engineering/deep-neural-networks/neural-network-architecture',
            'ai-for-engineering/deep-neural-networks/neural-network-from-scratch',
            'ai-for-engineering/deep-neural-networks/interview-readiness',
          ],
        },
        {
          type: 'category',
          label: 'Foundations of Regression',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/foundations-of-regression/intro' },
          items: [
            'ai-for-engineering/foundations-of-regression/linear-regression-line-ssr-gradient-descent',
            'ai-for-engineering/foundations-of-regression/why-logistic-regression',
            'ai-for-engineering/foundations-of-regression/sigmoid-function-logistic-regression',
            'ai-for-engineering/foundations-of-regression/logistic-regression-decision-boundaries',
            'ai-for-engineering/foundations-of-regression/intuition-behind-logistic-regression',
            'ai-for-engineering/foundations-of-regression/log-likelihood-instead-of-squared-error',
            'ai-for-engineering/foundations-of-regression/interview-readiness',
          ],
        },
        { type: 'html', value: '<span class="sidebar-divider">Vision & Sequences</span>' },
        {
          type: 'category',
          label: 'Deep Computer Vision (CNN)',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/deep-computer-vision-cnn/intro' },
          items: [
            'ai-for-engineering/deep-computer-vision-cnn/visual-revolution',
            'ai-for-engineering/deep-computer-vision-cnn/transformative-deep-learning-vision',
            'ai-for-engineering/deep-computer-vision-cnn/from-pixels-to-perception',
            'ai-for-engineering/deep-computer-vision-cnn/feature-detection-hierarchy',
            'ai-for-engineering/deep-computer-vision-cnn/learning-features-from-data',
            'ai-for-engineering/deep-computer-vision-cnn/preserving-spatial-structure-cnns',
            'ai-for-engineering/deep-computer-vision-cnn/filters-features-convolutions',
            'ai-for-engineering/deep-computer-vision-cnn/learning-to-see-cnns',
            'ai-for-engineering/deep-computer-vision-cnn/interview-readiness',
          ],
        },
        {
          type: 'category',
          label: 'Deep Sequence Modelling (RNN)',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/deep-sequence-modelling-rnn/intro' },
          items: [
            'ai-for-engineering/deep-sequence-modelling-rnn/foundations-of-deep-sequence-modeling',
            'ai-for-engineering/deep-sequence-modelling-rnn/from-static-networks-to-time-aware',
            'ai-for-engineering/deep-sequence-modelling-rnn/rnn-internal-mechanics',
            'ai-for-engineering/deep-sequence-modelling-rnn/bringing-sequence-modeling-real-world',
            'ai-for-engineering/deep-sequence-modelling-rnn/training-rnn-backprop-through-time',
            'ai-for-engineering/deep-sequence-modelling-rnn/training-an-rnn-in-pytorch',
            'ai-for-engineering/deep-sequence-modelling-rnn/interview-readiness',
          ],
        },
        { type: 'html', value: '<span class="sidebar-divider">Transformers</span>' },
        {
          type: 'category',
          label: 'Attention Is All You Need',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/attention-is-all-you-need/intro' },
          items: [
            'ai-for-engineering/attention-is-all-you-need/problem-with-rnns-and-lstms',
            'ai-for-engineering/attention-is-all-you-need/token-embeddings',
            'ai-for-engineering/attention-is-all-you-need/positional-embeddings',
            'ai-for-engineering/attention-is-all-you-need/attention',
            'ai-for-engineering/attention-is-all-you-need/self-attention',
            'ai-for-engineering/attention-is-all-you-need/multi-headed-attention',
            'ai-for-engineering/attention-is-all-you-need/causal-masking',
            'ai-for-engineering/attention-is-all-you-need/residual-connections',
            'ai-for-engineering/attention-is-all-you-need/layer-normalization',
            'ai-for-engineering/attention-is-all-you-need/feed-forward-neural-networks',
            'ai-for-engineering/attention-is-all-you-need/cross-attention',
            'ai-for-engineering/attention-is-all-you-need/encoder-stack',
            'ai-for-engineering/attention-is-all-you-need/decoder-stack',
            'ai-for-engineering/attention-is-all-you-need/encoder-decoder-transformer',
            'ai-for-engineering/attention-is-all-you-need/interview-readiness',
          ],
        },
        {
          type: 'category',
          label: 'Build and Train Your Own GPT-2',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/build-and-train-your-own-gpt2-model/intro' },
          items: [
            'ai-for-engineering/build-and-train-your-own-gpt2-model/problem-with-rnns-lstms',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/token-embeddings',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/positional-embeddings',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/attention-multi-head-attention',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/causal-masking',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/residual-connections',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/layer-normalization',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/feed-forward-neural-networks',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/generation-of-next-tokens',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/decoder-only-transformer',
            'ai-for-engineering/build-and-train-your-own-gpt2-model/interview-readiness',
          ],
        },
        { type: 'html', value: '<span class="sidebar-divider">Agentic AI</span>' },
        {
          type: 'category',
          label: 'Build a Multi-Agent Research Assistant',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/agentic-ai/intro' },
          items: [
            'ai-for-engineering/agentic-ai/intro',
            'ai-for-engineering/agentic-ai/01-bare-llm-loop',
            'ai-for-engineering/agentic-ai/02-tool-use',
            'ai-for-engineering/agentic-ai/03-react-reasoning',
            'ai-for-engineering/agentic-ai/04-planner',
            'ai-for-engineering/agentic-ai/05-parallel-executors',
          ],
        },
        { type: 'html', value: '<span class="sidebar-divider">Career</span>' },
        {
          type: 'category',
          label: 'MLE Interview',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/mle-interview/intro' },
          items: [
            'ai-for-engineering/mle-interview/intro',
            'ai-for-engineering/mle-interview/rubrics-and-playbook',
          ],
        },
        {
          type: 'category',
          label: 'AI Research',
          className: 'sidebar-course',
          link: { type: 'doc', id: 'ai-for-engineering/ai-research/intro' },
          items: ['ai-for-engineering/ai-research/aletheia-gemini-deep-think-math-research'],
        },
      ],
    },
    { type: 'html', value: '<span class="sidebar-writing-header">Writing & Talks</span>' },
    'ai-writing-and-talks/from-statistical-models-to-modern-ai-systems',
    'ai-writing-and-talks/what-should-we-learn-engineer-modern-ai',
  ],
};

export default sidebars;
