// Perceptron scene: x₁,x₂,x₃ → ∑wᵢxᵢ+b → σ(z) → ŷ
// All coordinates are in Excalidraw canvas units (px at 100% zoom).

const SEED = 42;
const FONT = 1; // Virgil (hand-drawn)

export const perceptronElements = [
  // ─── Title ────────────────────────────────────────────────────────────────
  {
    id: 'title',
    type: 'text',
    x: 40,
    y: 18,
    width: 520,
    height: 28,
    text: 'The Perceptron — one computational unit',
    fontSize: 20,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'top',
    strokeColor: '#1e293b',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },

  // ─── Input circles ────────────────────────────────────────────────────────
  // x₁
  {
    id: 'x1',
    type: 'ellipse',
    x: 48,
    y: 72,
    width: 68,
    height: 68,
    strokeColor: '#0284c7',
    backgroundColor: '#e0f2fe',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 1,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  {
    id: 'x1-label',
    type: 'text',
    x: 67,
    y: 97,
    width: 30,
    height: 20,
    text: 'x₁',
    fontSize: 18,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'middle',
    strokeColor: '#0369a1',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 2,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  // x₂
  {
    id: 'x2',
    type: 'ellipse',
    x: 48,
    y: 178,
    width: 68,
    height: 68,
    strokeColor: '#0284c7',
    backgroundColor: '#e0f2fe',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 3,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  {
    id: 'x2-label',
    type: 'text',
    x: 67,
    y: 203,
    width: 30,
    height: 20,
    text: 'x₂',
    fontSize: 18,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'middle',
    strokeColor: '#0369a1',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 4,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  // x₃
  {
    id: 'x3',
    type: 'ellipse',
    x: 48,
    y: 284,
    width: 68,
    height: 68,
    strokeColor: '#0284c7',
    backgroundColor: '#e0f2fe',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 5,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  {
    id: 'x3-label',
    type: 'text',
    x: 67,
    y: 309,
    width: 30,
    height: 20,
    text: 'x₃',
    fontSize: 18,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'middle',
    strokeColor: '#0369a1',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 6,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },

  // ─── Arrows: inputs → neuron ──────────────────────────────────────────────
  // x₁ → neuron
  {
    id: 'arrow-x1',
    type: 'arrow',
    x: 118,
    y: 106,
    width: 134,
    height: 106,
    points: [[0, 0], [134, 106]],
    strokeColor: '#475569',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 10,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
    startArrowhead: null,
    endArrowhead: 'arrow',
    startBinding: null,
    endBinding: null,
  },
  // w₁ label
  {
    id: 'w1-label',
    type: 'text',
    x: 144,
    y: 122,
    width: 26,
    height: 20,
    text: 'w₁',
    fontSize: 14,
    fontFamily: FONT,
    textAlign: 'left',
    verticalAlign: 'top',
    strokeColor: '#64748b',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 11,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  // x₂ → neuron (straight)
  {
    id: 'arrow-x2',
    type: 'arrow',
    x: 118,
    y: 212,
    width: 134,
    height: 0,
    points: [[0, 0], [134, 0]],
    strokeColor: '#475569',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 12,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
    startArrowhead: null,
    endArrowhead: 'arrow',
    startBinding: null,
    endBinding: null,
  },
  // w₂ label
  {
    id: 'w2-label',
    type: 'text',
    x: 158,
    y: 196,
    width: 26,
    height: 20,
    text: 'w₂',
    fontSize: 14,
    fontFamily: FONT,
    textAlign: 'left',
    verticalAlign: 'top',
    strokeColor: '#64748b',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 13,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  // x₃ → neuron
  {
    id: 'arrow-x3',
    type: 'arrow',
    x: 118,
    y: 318,
    width: 134,
    height: -106,
    points: [[0, 0], [134, -106]],
    strokeColor: '#475569',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 14,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
    startArrowhead: null,
    endArrowhead: 'arrow',
    startBinding: null,
    endBinding: null,
  },
  // w₃ label
  {
    id: 'w3-label',
    type: 'text',
    x: 144,
    y: 278,
    width: 26,
    height: 20,
    text: 'w₃',
    fontSize: 14,
    fontFamily: FONT,
    textAlign: 'left',
    verticalAlign: 'top',
    strokeColor: '#64748b',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 15,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },

  // ─── Neuron (∑ wᵢxᵢ + b) ─────────────────────────────────────────────────
  {
    id: 'neuron',
    type: 'ellipse',
    x: 252,
    y: 162,
    width: 100,
    height: 100,
    strokeColor: '#92400e',
    backgroundColor: '#fef3c7',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 20,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  {
    id: 'neuron-label',
    type: 'text',
    x: 260,
    y: 190,
    width: 84,
    height: 44,
    text: '∑ wᵢxᵢ\n+ b',
    fontSize: 15,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'middle',
    strokeColor: '#78350f',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 21,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },

  // ─── Arrow: neuron → output ───────────────────────────────────────────────
  {
    id: 'arrow-out',
    type: 'arrow',
    x: 352,
    y: 212,
    width: 88,
    height: 0,
    points: [[0, 0], [88, 0]],
    strokeColor: '#475569',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 30,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
    startArrowhead: null,
    endArrowhead: 'arrow',
    startBinding: null,
    endBinding: null,
  },
  // σ(z) label on arrow
  {
    id: 'sigma-label',
    type: 'text',
    x: 364,
    y: 192,
    width: 56,
    height: 20,
    text: 'f(z) = σ(z)',
    fontSize: 13,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'top',
    strokeColor: '#6d28d9',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 31,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },

  // ─── Output circle (ŷ) ────────────────────────────────────────────────────
  {
    id: 'output',
    type: 'ellipse',
    x: 440,
    y: 178,
    width: 68,
    height: 68,
    strokeColor: '#065f46',
    backgroundColor: '#d1fae5',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 40,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  {
    id: 'output-label',
    type: 'text',
    x: 458,
    y: 203,
    width: 32,
    height: 20,
    text: 'ŷ',
    fontSize: 20,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'middle',
    strokeColor: '#064e3b',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 41,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },

  // ─── Bias annotation ──────────────────────────────────────────────────────
  {
    id: 'bias-arrow',
    type: 'arrow',
    x: 302,
    y: 120,
    width: 0,
    height: 42,
    points: [[0, 0], [0, 42]],
    strokeColor: '#b45309',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 50,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
    startArrowhead: null,
    endArrowhead: 'arrow',
    startBinding: null,
    endBinding: null,
  },
  {
    id: 'bias-label',
    type: 'text',
    x: 310,
    y: 102,
    width: 20,
    height: 20,
    text: 'b',
    fontSize: 16,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'top',
    strokeColor: '#b45309',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 51,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },

  // ─── Caption callouts ─────────────────────────────────────────────────────
  {
    id: 'note-linear',
    type: 'text',
    x: 48,
    y: 368,
    width: 180,
    height: 20,
    text: '← inputs (features)',
    fontSize: 13,
    fontFamily: FONT,
    textAlign: 'left',
    verticalAlign: 'top',
    strokeColor: '#0369a1',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 60,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  {
    id: 'note-activation',
    type: 'text',
    x: 248,
    y: 368,
    width: 180,
    height: 20,
    text: '↑ linear + activation',
    fontSize: 13,
    fontFamily: FONT,
    textAlign: 'center',
    verticalAlign: 'top',
    strokeColor: '#78350f',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 61,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
  {
    id: 'note-output',
    type: 'text',
    x: 420,
    y: 368,
    width: 100,
    height: 20,
    text: 'prediction →',
    fontSize: 13,
    fontFamily: FONT,
    textAlign: 'right',
    verticalAlign: 'top',
    strokeColor: '#064e3b',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    roughness: 1,
    seed: SEED + 62,
    version: 1,
    versionNonce: 1,
    isDeleted: false,
    groupIds: [],
    frameId: null,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  },
];
